name: GitHub Release with APKs

on:
  push:
    tags:
    - 'v*'

env:
  compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
  compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
  compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout    
        uses: actions/checkout@v4
        
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false        

      - name: Upload AppsMonitor
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/AppsMonitor-1.9.2.apk
          asset_name: AppsMonitor-1.9.2.apk
          asset_content_type: application/vnd.android.package-archive          
